name: CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install
              run: npm ci

            - name: Run unit tests
              run: npm test

            - name: Run integration tests
              uses: cypress-io/github-action@v4
              with:
                  build: npm run build
                  start: npm start
                  wait-on: 'http://localhost:3000, http://localhost:3001'
